export const FETCH_TODO_LIST = 'FETCH_TODO_LIST';
export const FETCH_TODO_LIST_FAILED = 'FETCH_TODO_LIST_FAILED';
export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST';
export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
